name: mimetica
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - loguru
  - numpy
  - matplotlib
  - opencv
  - pip
  - pyqtgraph
  - pyside6
  - scikit-image[optional]
  - shapely
  - pip:
      - semver
      - -e .
